### PR TITLE
feat: add disclosureProps to ThemeEditor

### PR DESCRIPTION
**Pull request by panbenson**
apply the same changes from https://github.com/Hyperting/hypertheme-editor/pull/18 to `support/0.1.x` as suggested in https://github.com/Hyperting/hypertheme-editor/pull/18#issuecomment-1047196724

@it-nalon please let me know if you need help with updating documentation or anything 😄

### CODE REVIEW

**Comment by panbenson** [comment]
hi @it-nalon just following up with this, is it still possible to release this as a patch version (0.1.4)?

**Comment by it-nalon** [comment]
Hi @panbenson, yes, we'll publish the new release in a couple of days.
Sorry for the delay!

**Comment by it-nalon** [comment]
Hi @panbenson , we have published a release candidate with version number: `0.1.4-rc.0`.

Let me know if it's working for you!

**Comment by panbenson** [comment]
yeah this works great, thanks again for all the help @it-nalon!

**Pull request merged**
